const nodemailer = require('nodemailer');


const transporter = nodemailer.createTransport({
  service: 'gmail', 
  auth: {
    user: 'rentcycleplatform@gmail.com', 
    pass: 'wonu xqaa eyry ysxo',   
  },
});

/**
 * Sends a verification email to a user.
 * @param {string} userEmail The recipient's email address.
 * @param {string} verificationCode The 6-digit code to send.
 */
const sendVerificationEmail = async (userEmail, verificationCode) => {
  const mailOptions = {
    from: '"RentCycle" <rentcycleplatform@gmail.com>',
    to: userEmail,
    subject: 'Your RentCycle Verification Code',
    html: `
      <div style="font-family: sans-serif; text-align: center; padding: 20px;">
        <h2>Welcome to RentCycle!</h2>
        <p>Your verification code is:</p>
        <p style="font-size: 24px; font-weight: bold; letter-spacing: 5px; margin: 20px 0; background-color: #f0f0f0; padding: 10px; border-radius: 8px;">
          ${verificationCode}
        </p>
        <p>This code will expire in 15 minutes.</p>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`[EmailService] Verification email sent to ${userEmail}`);
  } catch (error) {
    console.error(`[EmailService] Error sending email to ${userEmail}:`, error);
    // In a real app, you might want to handle this error more gracefully
    throw new Error('Failed to send verification email.');
  }
};

// --- NEW FUNCTION ADDED ---
/**
 * Sends a password reset link to a user.
 * @param {string} to - The recipient's email address.
 * @param {string} link - The password reset link generated by Firebase.
 */
const sendPasswordResetEmail = async (to, link) => {
  const mailOptions = {
    from: `"RentCycle" <${process.env.EMAIL_USER || 'rentcycleplatform@gmail.com'}>`,
    to: to,
    subject: 'Reset Your RentCycle Password',
    text: `You requested a password reset. Click the following link to reset your password: ${link}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
        <h2 style="color: #333;">Password Reset Request</h2>
        <p style="font-size: 16px;">We received a request to reset your password. Click the button below to choose a new one. This link will expire shortly.</p>
        <a href="${link}" style="display: inline-block; background-color: #6a0dad; color: #ffffff; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-size: 16px; font-weight: bold; margin: 20px 0;">
          Reset Password
        </a>
        <p style="font-size: 14px; color: #777;">If you did not request this, please ignore this email.</p>
      </div>
    `,
  };

   try {
    await transporter.sendMail(mailOptions);
    console.log(`[EmailService] Password reset link sent to ${to}`);
  } catch (error) {
    console.error(`[EmailService] Error sending password reset email to ${to}:`, error);
    throw new Error('Failed to send password reset email.');
  }
};



module.exports = {
  sendVerificationEmail,
  sendPasswordResetEmail, 
};