const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'gmail', // Let Nodemailer handle host/port details automatically
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});
// --------------------------------------------

/**
 * Sends a verification email to a user.
 * @param {string} userEmail The recipient's email address.
 * @param {string} verificationCode The 6-digit code to send.
 */
const sendVerificationEmail = async (userEmail, verificationCode) => {
  const mailOptions = {
    from: `"RentCycle" <${process.env.EMAIL_USER}>`,
    to: userEmail,
    subject: 'Your RentCycle Verification Code',
    html: `
      <div style="font-family: sans-serif; text-align: center; padding: 20px;">
        <h2>Welcome to RentCycle!</h2>
        <p>Your verification code is:</p>
        <p style="font-size: 24px; font-weight: bold; letter-spacing: 5px; margin: 20px 0; background-color: #f0f0f0; padding: 10px; border-radius: 8px;">
          ${verificationCode}
        </p>
        <p>This code will expire in 15 minutes.</p>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`[EmailService] Verification email sent to ${userEmail}`);
  } catch (error) {
    console.error(`[EmailService] Error sending email to ${userEmail}:`, error);
    // Throw error so the frontend knows it failed
    throw new Error('Failed to send verification email.');
  }
};


/**
 * Sends a password reset link to a user.
 * @param {string} to - The recipient's email address.
 * @param {string} link - The password reset link generated by Firebase.
 */
const sendPasswordResetEmail = async (to, link) => {
  const mailOptions = {
    from: `"RentCycle" <${process.env.EMAIL_USER}>`,
    to: to,
    subject: 'Reset Your RentCycle Password',
    text: `You requested a password reset. Click the following link to reset your password: ${link}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
        <h2 style="color: #333;">Password Reset Request</h2>
        <p style="font-size: 16px;">We received a request to reset your password. Click the button below to choose a new one. This link will expire shortly.</p>
        <a href="${link}" style="display: inline-block; background-color: #6a0dad; color: #ffffff; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-size: 16px; font-weight: bold; margin: 20px 0;">
          Reset Password
        </a>
        <p style="font-size: 14px; color: #777;">If you did not request this, please ignore this email.</p>
      </div>
    `,
  };

   try {
    await transporter.sendMail(mailOptions);
    console.log(`[EmailService] Password reset link sent to ${to}`);
  } catch (error) {
    console.error(`[EmailService] Error sending password reset email to ${to}:`, error);
    throw new Error('Failed to send password reset email.');
  }
};


/**
 * Sends a contact form submission to the admin email.
 * @param {object} formData - The form data { name, email, subject, message }
 */
const sendContactFormEmail = async (formData) => {
  const { name, email, subject, message } = formData;

  const mailOptions = {
    from: `"RentCycle Contact Form" <${process.env.EMAIL_USER}>`,
    to: process.env.EMAIL_USER, // Send to yourself (Admin)
    subject: `New Contact Form Submission: ${subject}`,
    replyTo: email, // Set the 'reply-to' to the user's email so you can hit reply
    text: `You have a new message from ${name} (${email}).\n\nSubject: ${subject}\n\nMessage:\n${message}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
        <h2 style="color: #333;">New Contact Form Message</h2>
        <p style="font-size: 16px;">You have a new message from <strong>${name}</strong> (${email}).</p>
        <hr style="border: 0; border-top: 1px solid #eee;">
        <h3 style="color: #555;">Subject: ${subject}</h3>
        <p style="font-size: 16px; line-height: 1.6; background: #f9f9f9; padding: 15px; border-radius: 5px;">
          ${message.replace(/\n/g, '<br>')}
        </p>
        <hr style="border: 0; border-top: 1px solid #eee;">
        <p style="font-size: 14px; color: #777;">You can reply directly to this email to contact the user.</p>
      </div>
    `,
  };

   try {
    await transporter.sendMail(mailOptions);
    console.log(`[EmailService] Contact form email sent successfully from ${email}`);
  } catch (error) {
    console.error(`[EmailService] Error sending contact form email:`, error);
    throw new Error('Failed to send contact form email.');
  }
};

module.exports = {
  sendVerificationEmail,
  sendPasswordResetEmail,
  sendContactFormEmail,
};